### ISSUE TITLE
rcd shows wrong sort order with version `_rc`

### ISSUE THREAD

**Issue by arthurzam** [ionenwks/iwdevtools#12]
I think I can "complain" and report this super low priority issue just because of the high level product that is `iwdevtools`

When I performed `rcd dev-python/exceptiongroup` on gentoo tree, the version where in wrong order:

```
$ rcd exceptiongroup 
 > ~/dev/gentoo/dev-python/exceptiongroup
 D Backport of PEP 654 (exception groups) (1.0.0_rc9)
 H https://github.com/agronholm/exceptiongroup/
 H https://pypi.org/project/exceptiongroup/
 G https://packages.gentoo.org/packages/dev-python/exceptiongroup
 G https://bugs.gentoo.org/buglist.cgi?quicksearch=dev-python%2Fexceptiongroup
 M python@gentoo.org
 + Manifest
 + exceptiongroup-1.0.0.ebuild
 + exceptiongroup-1.0.0_rc8.ebuild
 + exceptiongroup-1.0.0_rc9.ebuild
 + metadata.xml
```

While the correct ordering should be:

```
pkgdev showkw 
           a a   a     l       p r   s
           l m   r h i o m m   p i s p   e s r
           p d a m p a o 6 i p c s 3 a x a l e
           h 6 r 6 p 6 n 8 p p 6 c 9 r 8 p o p
           a 4 m 4 a 4 g k s c 4 v 0 c 6 i t o
---------------------------------------------------
 1.0.0_rc8 ~ + + + + ~ o ~ ~ + + ~ ~ + + 8 0 gentoo
 1.0.0_rc9 ~ ~ ~ ~ ~ ~ o ~ ~ ~ ~ ~ ~ ~ ~ 8 0 gentoo
 1.0.0     ~ ~ ~ ~ ~ ~ o ~ ~ ~ ~ ~ ~ ~ ~ 8 0 gentoo
```

I'm fine if you just close it as won't fix, but just reported it in case it can be easily fixed?

**Comment by ionenwks** [comment]
This is not really iwdevtools, this is just a basic default/example for --run:
```
  -R, --run=COMMAND   If atom matches a package, run COMMAND then exit with
                      its status, see *Running Commands* for details
                      (default: ls -1v --color=always)
```
People are encouraged to run their own scripts to display whatever is useful to them (see README.rst for some examples), and either keep running `ls` in it or some other commands as they prefer.

**Comment by ionenwks** [comment]
Of course, you can also do `rcd --run="pkgdev showkw"` and use `~/.config/iwdevtools/repo-cd.conf` to make it default :eyes:
