### ISSUE TITLE
A (big?) issue with `vdb-set_libneed`

### ISSUE THREAD

**Issue by kuraga** [ionenwks/iwdevtools#15]
Good day!

https://github.com/ionenwks/iwdevtools/blob/694324b315e567dcdc4ff8b28298e8ceea977687/scripts/qa-vdb#L621-L626

Let's try:

```bash
$ req=(libtiff.so.5) && qfile -CqvP -- "${req[@]}" && echo "qfile passed" || echo  "qfile not passed"
qfile not passed
```
Checking of `libtiff.so.5` is failed - `qa-vdb` will fail.

```bash
$ req=(/lib64/ld-linux-x86-64.so.2 libtiff.so.5) && qfile -CqvP -- "${req[@]}" && echo "qfile passed" || echo  "qfile not passed"
sys-libs/glibc-2.36-r5
qfile passed
```
Checking of `libtiff.so.5` is omitted - `qa-vdb` will _pass!!!!!!_

(So, `qa-vdb` fails if and only if there is _exactly one_ need lib and this lib is doesn't have a provider.)

Thoughts?

Thanks!

**Comment by ionenwks** [comment]
`die "qfile couldn't find any dependencies of '${1}' [...]`'s `any` implies that it's okay if some were not found. The `die` is more or less just a sanity check to see if qfile works at all.

Some paths are also tentatively injected to handle usr-merge full knowing that the path may not exist in /var/db/pkg (aka it /will/ fail).

Not something I'm overly happy with (kinda fragile), but it's not a problem per se. Portage already checks for unresolved soname dependencies and reports them, so it's not really something we need to worry about here and do a 2nd report of. We just need to get the list of packages for libraries that qfile did manage to find.

**Comment by kuraga** [comment]
@ionenwks , thanks for reply! But suppose an atom needs 100 libs. `qfile` finds 1 only. User will get  OK. What's the benefit of the information "you need 1 more dep" _(without any warnings - the key)_?

**Comment by ionenwks** [comment]
> @ionenwks , thanks for reply! But suppose an atom needs 100 libs. `qfile` finds 1 only. User will get OK. What's the benefit of the information "you need 1 more dep" _(without any warnings - the key)_?

Then portage will report that 99 libs were not found (even without iwdevtools), what more do you need?

**Comment by ionenwks** [comment]
Unfortunately as long as need the usr-merge workaround, I don't think there's a good way to know which libs will fail and which will not. Doing separate qfile calls would also be more expensive.

**Comment by kuraga** [comment]
> Then portage will report that 99 libs were not found

Nothing, if it does. Say, please, how can I get it via portage?
Thanks!
