### ISSUE TITLE
VDB: detected possibly incorrect RDEPEND: dev-libs/boost:= <

### ISSUE THREAD

**Issue by juippis** [ionenwks/iwdevtools#17]
Wasn't boost one of those packages that needed to be in RDEPEND even though it doesn't directly link to anything? Maybe boost should be excluded from the checks?

Note to self: this happened with media-gfx/librecad-2.2.0.

**Comment by thesamesam** [comment]
This is tricky. There's two issues:
1. It depends on which Boost modules are being used. They might be header only _at the moment_ and the risk of DEPEND only is that it becomes stale and in a subsequent release of the software (not boost), someone doesn't notice they now use more. Bit like Qt in that Boost is often a bit of a way of life.
2. If we're using a header-only library, there's no need in terms of runtime stability to recompile, but there is a need to recompile to get bug fixes.

@soapgentoo

**Comment by ionenwks** [comment]
Either way, excluding from checks sound a bit dodgy -- it could also be genuinely not used. Regardless of how prefer this is handled, information that it's not using the shared libraries is still useful, and as usual the suggestions to remove deps should always go through maintainer judgement.
