### ISSUE TITLE
division by 0 (error token is "snew")

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [ionenwks/iwdevtools#2]
when emerging `dev-python/spyder-terminal-1.1.0` and other packages I get
```
>>> Merging dev-python/spyder-terminal-1.1.0 to /                                                                                                                                                                                           
 * removing unneeded *.la files
 * qa-cmp: running 'qa-cmp' failed (disable with QA_CMP=n)                                                                                                                                       
 * /usr/bin/qa-cmp: line 743: 100 - 100 * sold / snew: division by 0 (error token is "snew")
```

**Comment by ionenwks** [comment]
Looks normal on my end:
```
 * QA: comparing =dev-python/spyder-terminal-1.0.0-r1 with dev-python/spyder-terminal-1.1.0/image
 *  FILES:-usr/lib/python3.9/site-packages/spyder_terminal/server/static/components/path-parse/test.js
 * ------> FILES(-1)
```
But there is paths for this to be possible. Currently it ignores errors on `du(1)` given it returns failure if even 1 file got a permission denied (which is expected as normal for some packages), but in the event all files got permission denied or it (really) failed, would end up with snew = 0.

I think I'll look at using VDB/SIZE instead and skip using `du(1)`, should be more failproof. Kinda slipped I could use that given qa-cmp is not really aimed at VDB unlike qa-vdb.

Not that this says much as to why it failed for you.
