### ISSUE TITLE
qa-vdb: qfile couldn't find dependencies on usr-merged system due to glibc VDB CONTENTS pointing to /lib* and not /usr/lib*

### ISSUE THREAD

**Issue by gyakovlev** [ionenwks/iwdevtools#5]
a corner case which is probably worth handling:

packages with minimal deps

`app-text/fzy-1.0-r1`

```
lddtree /usr/bin/fzy
fzy => /usr/bin/fzy (interpreter => /lib64/ld64.so.2)
    libpthread.so.0 => /usr/lib64/libpthread.so.0
        ld64.so.2 => /lib64/ld64.so.2
    libc.so.6 => /usr/lib64/libc.so.6
```

some rust apps that don't link to anything trigger that too:

```
qa-vdb hyperfine
Error: qfile couldn't find dependencies of 'app-benchmarks/hyperfine-1.12.0' (may be due to binpkgs ordering) (qa-vdb:vdb-set_libneed:604)

lddtree /usr/bin/hyperfine 
hyperfine => /usr/bin/hyperfine (interpreter => /lib64/ld64.so.2)
    libgcc_s.so.1 => /usr/lib/gcc/powerpc64le-unknown-linux-gnu/11.2.0/libgcc_s.so.1
    libpthread.so.0 => /usr/lib64/libpthread.so.0
        ld64.so.2 => /lib64/ld64.so.2
    libdl.so.2 => /usr/lib64/libdl.so.2
    libc.so.6 => /usr/lib64/libc.so.6
```

**Comment by ionenwks** [comment]
Hm, can't reproduce with these atm (on amd64), but this would happen if it's using a library that doesn't have an associated package recorded in /var/db/pkg.

Does qfile fail on any of these libraries? i.e.
```
qfile -CqvP libpthread.so.0 &&
qfile -CqvP ld64.so.2 &&
qfile -CqvP libc.so.6 || echo failed
```
Also, what's in /var/db/pkg/app-text/fzy-1.0-r1/REQUIRES? It's from where it gets the library list rather than scanelf/lddtree, in my case it only has `x86_64: libc.so.6` and lddtree is just
```
fzy => /usr/bin/fzy (interpreter => /lib64/ld-linux-x86-64.so.2)
    libc.so.6 => /lib64/libc.so.6
        ld-linux-x86-64.so.2 => /lib64/ld-linux-x86-64.so.2
```
(as-needed likely discarded the stub libpthread from glibc-2.34)

qfile did give me grief when I didn't have an actual libc in the ROOT used for qa-vdb tests, but I doubt it's what I'm seeing here :)

fwiw --ignore-uninstalled / -u can bypass that error, although it's not a real fix (intended for when using package.provided or stuff like that). Alternatively, problematic libraries can be excluded in /etc/iwdevtools/qa-vdb.exclude-lib

**Comment by ionenwks** [comment]
Also, please retry with just the command to ensure not any strange ordering issues, aka
`$ qa-vdb --confirm fzy`

**Comment by gyakovlev** [comment]
yeah some linking differs on other platforms

all those belong to glibc
```
qfile -CqvP libpthread.so.0 &&
qfile -CqvP ld64.so.2 &&
qfile -CqvP libc.so.6 || echo failed
sys-libs/glibc-2.33-r7
sys-libs/glibc-2.33-r7
sys-libs/glibc-2.33-r7
```

```
cat  /var/db/pkg/app-text/fzy-1.0-r1/REQUIRES
ppc_64: libc.so.6 libpthread.so.0
```

```
$  qa-vdb --confirm fzy
Error: qfile couldn't find dependencies of 'app-text/fzy-1.0-r1' (may be due to binpkgs ordering) (qa-vdb:vdb-set_libneed:604)
```

I can give access to power machine if you want to poke yourself.

**Comment by gyakovlev** [comment]
and default exclude already ships has `sys-libs/glibc` or it's to skip checks for this package?
I installed tools first time today, still poking/reading.

**Comment by gyakovlev** [comment]
ah, I might have an important detail here =)
it's usr-merged system

```
realpath /lib64/ld64.so.2
/usr/lib64/ld-2.33.so
```

but lddtree omits /usr component

but maybe a red herring too. idk, haven't looked deep yet.

**Comment by gyakovlev** [comment]
on arm64 (not merged usr) it's fine
```
lddtree /usr/bin/fzy
fzy => /usr/bin/fzy (interpreter => /lib/ld-linux-aarch64.so.1)
    libpthread.so.0 => /lib64/libpthread.so.0
    libc.so.6 => /lib64/libc.so.6
    ld-linux-aarch64.so.1 => /lib/ld-linux-aarch64.so.1
    
REQUIRES
arm_64: ld-linux-aarch64.so.1 libc.so.6 libpthread.so.0
```

**Comment by ionenwks** [comment]
Actually, this might matter, it tries to find the real paths of libraries based on /etc/ld.so.conf and perhaps it got it wrong.

Please try with 2c507933e66219d212c3e35c7de8ae186dd3b3e0

**Comment by gyakovlev** [comment]
yeah can't reproduce on ppc64 with split usr. trying

**Comment by gyakovlev** [comment]
```
 $ qa-vdb hyperfine
Error: qfile couldn't find dependencies of 'app-benchmarks/hyperfine-1.12.0' (may be due to binpkgs ordering), tried to find: '/usr/lib64/libc.so.6 /usr/lib64/libdl.so.2 /usr/lib64/libpthread.so.0' (qa-vdb:vdb-set_libneed:604)
 $ qa-vdb fzy
Error: qfile couldn't find dependencies of 'app-text/fzy-1.0-r1' (may be due to binpkgs ordering), tried to find: '/usr/lib64/libc.so.6 /usr/lib64/libpthread.so.0' (qa-vdb:vdb-set_libneed:604)
```

**Comment by ionenwks** [comment]
I imagine that this fails now:
`qfile -CqvP /usr/lib64/libc.so.6 || echo failed`
Given it's not what is recorded in glibc's /var/db/pkg

**Comment by gyakovlev** [comment]
yeah literally wanted to comment that
qfile /usr/lib64/libc.so.6  is empty

or with your command obviously too
```
qfile -CqvP /usr/lib64/libc.so.6 || echo failed
failed
```

**Comment by gyakovlev** [comment]
```
cat /var/db/pkg/sys-libs/glibc-2.33-r7/CONTENTS  | grep libc.so.6
sym /lib64/libc.so.6 -> libc-2.33.so 1641777668
```

**Comment by ionenwks** [comment]
I could add a dirty usr-merge workaround, although optimal would be for /var/db/pkg to have the right information, but that'd require a USE=-split-usr on glibc

**Comment by gyakovlev** [comment]
looks like portage records file locations pre-merge to filesystem and does not resolve real locations after image is merged.
idk about useflag, it's not super-important, I can simply shut up the warning and ignore libc.so.6 or anything glibc provides, since it's implicit anyway.
but something to keep in mind.

**Comment by ionenwks** [comment]
It's a simple workaround anyway, so why not. I'll add a thing soon'ish

**Comment by ionenwks** [comment]
Added b29efa293215de2abd44f7439a05e542ecfc7c45, please check if it helps.

**Comment by ionenwks** [comment]
I *think* everything else will work fine, that it found the real path to libc means qa-vdb itself recognizes it as valid -- it's just qfile that's confused.

**Comment by gyakovlev** [comment]
thanks, it works so far on merged system.
