### ISSUE TITLE
qa-cmp can't handle files with $ in them (line 743: StreamGobbler: unbound variable)

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [ionenwks/iwdevtools#7]
I found this in the log after emerging libreoffice
`/usr/bin/qa-cmp: line 743: StreamGobbler: unbound variable`

**Comment by ionenwks** [comment]
Thanks, reproduced.. albeit I'm amazed that `[[ -v newindex[${file}] ]]` is an issue if `${file}` is `/path/to/some$file` with `$`, rather odd bash behavior and seems quoting it doesn't help either.

I'll experiment a bit more for a workaround.

**Comment by ionenwks** [comment]
Guess an alternate fix could be single quotes `[[ -v 'newindex[${file}]' ]]`, but given I don't see this behavior documented by bash (not that I looked in-depth, someone else may know better) I think I'll pass on using that...
